### ISSUE TITLE
reorg_layer.cu Line 52

### ISSUE THREAD

**Issue by xmfbit** [hustzxd/yolo2_in_caffe#11]
这行你写错了，应该是`bottom_blob->mutable_gpu_diff()`。

**Comment by ryusaeba** [comment]
@xmfbit  do you already test your fix? or original reorg_layer.cu is Ok?

**Comment by xmfbit** [comment]
@ryusaeba Hi, the implementation of reorg should be ok. But I don't recommend you to reuse this repo because it has been not maintained for a long time. You can find other reliable implementations of YOLO using Caffe in GitHub.

**Comment by ryusaeba** [comment]
@xmfbit Thanks! Per your suggestion, I will merge its reorg_layer.cu/cpp/hpp into my local Caffe. Do you know other reliable implementation of YOLO using CAFFE? If you have, please share with me. Many Thanks!

**Comment by ryusaeba** [comment]
Originally, I found https://github.com/gklz1982/caffe-yolov2. Then link to this.

**Comment by ryusaeba** [comment]
@xmfbit  sorry for bother you again. Or maybe you can share your reorg layer with me :)

**Comment by xmfbit** [comment]
@ryusaeba You can use reorg layer code in this repo.

**Comment by xmfbit** [comment]
@ryusaeba you can refer to this: https://github.com/longcw/yolo2-pytorch/blob/master/layers/reorg/src/reorg_cpu.c Sorry but I have been not working on YOLO for a lone time and I don't have the ownership of this repo.

**Comment by ryusaeba** [comment]
@xmfbit  T[he link you pasted](https://github.com/longcw/yolo2-pytorch/blob/master/layers/reorg/src/reorg_cpu.c), I found I have some misunderstanding about reorg_layer. I thought reorg_layer is to transfer 3x8x8 to 6x4x4 when using stride 2, right? If I am wrong, please correct me. 
 My understanding is out_c should be equal to c*(stride*stride), right?

**Comment by xmfbit** [comment]
@ryusaeba Yes, you are right. But a little mistake, not `6x4x4`, should be `12x4x4`. When doing forward computing, the channels grows, see the paper: "turns the 26 × 26 × 512 feature map into a 13 × 13 × 2048 feature map, which can be concatenated with the original features. "

**Comment by xmfbit** [comment]
@ryusaeba  Reorg layer is used to match the dimension of two different feature map. One is from a straightforward path and the other one run through several convulution layer, increasing channels and reducing spatial size.

**Comment by ryusaeba** [comment]
@xmfbit  thanks for your detail explanation. your explanation is exactly same as what I thought. 
yes, you are right. 3x8x8 should be 12x4x4 when using stride=2. 
But according the link you pasted, the code is out_c = c**/**(stride*stride); so I would like to confirm this.

**Comment by xmfbit** [comment]
@ryusaeba It can be do forward computing and backward computing by setting the variable `forward`. Yes, the name of the variable is somewhat strange and confusing. When `forward == False`, it do forward computing. When `forward == True`, it do backward computing (gradient back propagation). 

See this: https://github.com/longcw/yolo2-pytorch/blob/master/layers/reorg/reorg_layer.py#L19. When do forward computing, just let `foward=0`.

**Comment by ryusaeba** [comment]
@xmfbit  Thanks for discussing with me. Many Thanks!
