### ISSUE TITLE
Coule you tell me the version of CUDA and cudnn you used?

### ISSUE THREAD

**Issue by laixinn** [hustzxd/yolo2_in_caffe#13]

**Comment by hustzxd** [comment]
Hi, this project has not been updated for a long time. And YOLOv2 training is not supported, by the way, the code is poor. If you don't need training, and you really want this code, please let me know, I will give you a private version. Thank you.

**Comment by laixinn** [comment]
Yes i don't need training.I aim to convert the .weights file to .caffemodel file.

**Comment by laixinn** [comment]
And my email is 865809639@qq.com. Thank you.

**Comment by hustzxd** [comment]
Ok, please give me some time to prepare it. Maybe tomorrow.
